application: ming-jonny
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /stylesheets
  static_dir: stylesheets

- url: /
  script: main.app

- url: /callback
  script: callback.app


libraries:
- name: webapp2
  version: "2.5.1"
- name: jinja2
  version: latest
- name: ssl
  version: latest
